### ISSUE TITLE
Add suggestions when user is searching I'd and Improve the navbar

### ISSUE THREAD

**Issue by SmrutiRanjan-L** [CareerDevelopmentHub/GitHub-Analyser#2]

**Comment by kaal-coder** [comment]
Hello @SmrutiRanjan-L 
Can I do this?

**Comment by SmrutiRanjan-L** [comment]
Yeah, you can. Provide a preview SS before making PR.

**Comment by kaal-coder** [comment]
Okay. Will do so.

**Comment by kaal-coder** [comment]
![image](https://user-images.githubusercontent.com/85815858/194209212-d532983e-b777-4607-acc5-e682b1c3971d.png)

![image](https://user-images.githubusercontent.com/85815858/194209270-26e2cc8a-c7c1-42c9-bf19-503bd962ceaa.png)


suggestions when the user is searching I'd and Improved the navbar.

**Comment by SmrutiRanjan-L** [comment]
Great. It is as expected. Go for making a PR.

**Comment by kaal-coder** [comment]
Thank you.
